import type { SupabaseClient } from "@supabase/supabase-js";
import { DOCUMENTS_BUCKET, buildStoragePath } from "@/lib/supabase/storage";
import { uploadWithProgress } from "@/features/documents/storage-upload";

const GENERIC_UPLOAD_ERROR = "Upload failed. Please try again.";

type UploadResult =
  | { ok: true; documentId: string }
  | { ok: false; error: string };

export async function uploadCloudDocument(
  supabase: NonNullable<SupabaseClient>,
  file: File,
  folderId: string | null,
  onProgress?: (percent: number) => void,
): Promise<UploadResult> {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return { ok: false, error: "You need to sign in to upload documents." };
  }

  const documentId = crypto.randomUUID();
  const storagePath = buildStoragePath(user.id, documentId, file.name);

  try {
    await uploadWithProgress(supabase, storagePath, file, onProgress);
  } catch (uploadError) {
    return {
      ok: false,
      error:
        uploadError instanceof Error &&
        uploadError.name === "StorageUploadError"
          ? uploadError.message
          : GENERIC_UPLOAD_ERROR,
    };
  }

  const { error: insertError } = await supabase.from("documents").insert({
    id: documentId,
    user_id: user.id,
    folder_id: folderId,
    name: file.name,
    file_type: "pdf",
    mime_type: "application/pdf",
    size_bytes: file.size,
    storage_path: storagePath,
  });

  if (insertError) {
    await supabase.storage.from(DOCUMENTS_BUCKET).remove([storagePath]);
    return { ok: false, error: GENERIC_UPLOAD_ERROR };
  }

  return { ok: true, documentId };
}

type DeleteResult = { ok: boolean; error?: string };

export async function deleteCloudDocument(
  supabase: NonNullable<SupabaseClient>,
  documentId: string,
): Promise<DeleteResult> {
  const { data: row, error: fetchError } = await supabase
    .from("documents")
    .select("id, name, storage_path")
    .eq("id", documentId)
    .maybeSingle();

  if (fetchError || !row) {
    return { ok: false, error: "This document is no longer available." };
  }

  if (row.storage_path) {
    const { error: storageError } = await supabase.storage
      .from(DOCUMENTS_BUCKET)
      .remove([row.storage_path]);
    if (storageError) {
      return {
        ok: false,
        error:
          "The document could not be removed from storage. Please try again.",
      };
    }
  }

  const { error: deleteError } = await supabase
    .from("documents")
    .delete()
    .eq("id", documentId);

  if (deleteError) {
    return {
      ok: false,
      error:
        "The file was removed from storage but its record could not be deleted. Please try again.",
    };
  }

  return { ok: true };
}

export async function moveCloudDocument(
  supabase: NonNullable<SupabaseClient>,
  documentId: string,
  folderId: string | null,
): Promise<{ ok: boolean; error?: string }> {
  const { error } = await supabase
    .from("documents")
    .update({ folder_id: folderId })
    .eq("id", documentId);

  if (error) {
    return {
      ok: false,
      error: "Could not move the document. Please try again.",
    };
  }
  return { ok: true };
}

export async function renameCloudDocument(
  supabase: NonNullable<SupabaseClient>,
  documentId: string,
  name: string,
): Promise<{ ok: boolean; error?: string }> {
  const { error } = await supabase
    .from("documents")
    .update({ name })
    .eq("id", documentId);

  if (error) {
    return {
      ok: false,
      error: "Could not rename the document. Please try again.",
    };
  }
  return { ok: true };
}

export async function markDocumentOpened(
  supabase: NonNullable<SupabaseClient>,
  documentId: string,
): Promise<void> {
  await supabase
    .from("documents")
    .update({ last_opened_at: new Date().toISOString() })
    .eq("id", documentId);
}

export type CloudSaveErrorCode =
  | "auth"
  | "missing"
  | "stale"
  | "invalid"
  | "storage"
  | "metadata";

export type CloudSaveResult =
  | { ok: true }
  | { ok: false; error: string; code: CloudSaveErrorCode };

type SaveOptions = {
  expectedUpdatedAt?: string | null;
  force?: boolean;
  onProgress?: (percent: number) => void;
};

/**
 * Replaces the cloud document's stored PDF with freshly generated bytes.
 *
 * Sequence: ownership check (RLS select) -> structural validation of the
 * generated PDF -> upsert the replacement onto the SAME storage path ->
 * update size_bytes (updated_at is maintained by the set_updated_at
 * trigger). The existing object is never deleted first, so a failed
 * upload preserves the current cloud document. The stale check compares
 * the metadata updated_at snapshot taken when the document was opened;
 * force bypasses it after the user confirms.
 */
export async function saveCloudDocument(
  supabase: NonNullable<SupabaseClient>,
  documentId: string,
  bytes: Uint8Array,
  options: SaveOptions = {},
): Promise<CloudSaveResult> {
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return { ok: false, error: "You need to sign in to save.", code: "auth" };
  }

  const { data: row, error: rowError } = await supabase
    .from("documents")
    .select("id, name, storage_path, updated_at")
    .eq("id", documentId)
    .maybeSingle();

  if (rowError || !row || !row.storage_path) {
    return {
      ok: false,
      error: "This document is no longer available.",
      code: "missing",
    };
  }

  if (
    !options.force &&
    options.expectedUpdatedAt &&
    row.updated_at !== options.expectedUpdatedAt
  ) {
    return {
      ok: false,
      error: "This document was changed after you opened it.",
      code: "stale",
    };
  }

  if (bytes.byteLength === 0) {
    return {
      ok: false,
      error: "The edited PDF could not be generated.",
      code: "invalid",
    };
  }

  try {
    const { PDFDocument } = await import("pdf-lib");
    const doc = await PDFDocument.load(bytes, { updateMetadata: false });
    if (doc.getPageCount() === 0) {
      return {
        ok: false,
        error: "The edited PDF could not be generated.",
        code: "invalid",
      };
    }
  } catch {
    return {
      ok: false,
      error: "The edited PDF could not be generated.",
      code: "invalid",
    };
  }

  try {
    await uploadWithProgress(
      supabase,
      row.storage_path,
      new File([bytes as BlobPart], row.name, { type: "application/pdf" }),
      options.onProgress,
      { upsert: true },
    );
  } catch (uploadError) {
    return {
      ok: false,
      error:
        uploadError instanceof Error &&
        uploadError.name === "StorageUploadError"
          ? uploadError.message
          : "Save failed. Your existing cloud document was preserved.",
      code: "storage",
    };
  }

  const { error: updateError } = await supabase
    .from("documents")
    .update({ size_bytes: bytes.byteLength })
    .eq("id", documentId);

  if (updateError) {
    return {
      ok: false,
      error:
        "The file was saved, but the document record could not be updated. Please try again.",
      code: "metadata",
    };
  }

  return { ok: true };
}

export async function downloadCloudDocument(
  supabase: NonNullable<SupabaseClient>,
  row: { name: string; storage_path: string | null },
): Promise<{ ok: boolean; error?: string }> {
  if (!row.storage_path) {
    return { ok: false, error: "This document is no longer available." };
  }

  const { data, error } = await supabase.storage
    .from(DOCUMENTS_BUCKET)
    .download(row.storage_path);

  if (error || !data) {
    return {
      ok: false,
      error: "Could not download the document. Please try again.",
    };
  }

  const url = URL.createObjectURL(data);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = row.name;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
  return { ok: true };
}
