-- RamSpace Phase 5: cloud PDF replacement.
--
-- Phase 5 saves edited PDFs back to the cloud by upserting the newly
-- generated bytes onto the document's existing storage path. Supabase's
-- upsert executes an INSERT ... ON CONFLICT (bucket_id, name) DO UPDATE,
-- which Postgres evaluates through BOTH the INSERT and the UPDATE policy
-- on storage.objects. The INSERT policy already exists (0003); this
-- migration adds the matching UPDATE policy.
--
-- The policy is identical in spirit to the others: scoped to the
-- "documents" bucket AND the first path segment must equal the
-- authenticated user id. This does not widen access — users can only
-- replace objects they own, and files are never modified in place for
-- anyone else.

create policy "documents_storage_update_own"
  on storage.objects
  for update
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
  )
  with check (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = (select auth.uid()::text)
  );
